# Generated by Django 4.1 on 2022-11-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarBasicInfo',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('chinese_name', models.TextField()),
                ('gender', models.TextField()),
                ('department', models.TextField()),
                ('center', models.TextField()),
                ('title', models.TextField()),
                ('degree', models.TextField()),
                ('job', models.TextField()),
                ('field', models.TextField()),
                ('organization', models.TextField()),
                ('introduction', models.TextField()),
                ('thanks_paper', models.TextField()),
                ('mag_paper', models.TextField()),
                ('co_scholar', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
