# Generated by Django 4.1 on 2022-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudents',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('students', models.TextField()),
            ],
        ),
    ]
