# Generated by Django 4.1 on 2022-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_paperreferences_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='by_author',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
