# Generated by Django 4.1 on 2022-11-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_papers_by_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperReferences',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
