# Generated by Django 4.1 on 2022-11-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_paperreferences_papers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperReferences',
        ),
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
